### ISSUE TITLE
Suggestion/question.

### ISSUE THREAD

**Issue by MarioMey** [joelgraff/obs-deluxe-countdown#2]
I like this script (I prefer python than lua)... I will use it but I would like to use it as MM:SS (04:54), not HH:MM:SS (00:04:54).

What I need to modify? I know Python, but at naked eye, I didn't find what to change.

Suggestion: a field in properties to change the format as "%HH:%MM" or "%H:%M:%S" or "%SS.%CC".

**Comment by joelgraff** [comment]
The implementation is a bit mixed up, partly because of the way OBS calls the script, partly because I've never written a script for OBS before. :)

Your suggestion is a good one - I opted not to do it originally because it wasn't necessary for me.  I'll take a look at it, though, and see if I can work something out in the next few days...

**Comment by MarioMey** [comment]
Thanks man! I will use it for a 15 minutes waiting room for Zoom meetings. I would like the people to see "8:34" when there's 8 minutes 34 seconds to start the meeting.

Also, if you can't do it "in the next few days", I would like to know what the last string that OBS uses to print is and, by using some code, change it. Example:

    if string.startswith('00:'):
        string = string[3:]
    elif string.startswith('00:0'):
        string = string[4:]
    elif string.startswith('00:00:'):
        string = string[6:]

Or, better (not tested):

    if string.startswith('00:00:0'):
        string = string[7:] + ' seconds'
    elif string.startswith('00:00:'):
        string = string[6:] + ' seconds'
    elif string.startswith('00:0'):
        string = string[4:6] + ' minutes\n' + string[6:8] + ' seconds'
    elif string.startswith('00:'):
        string = string[3:6] + ' minutes\n' + string[6:8] + ' seconds'

**Comment by joelgraff** [comment]
Pull from master and see what you think.  I've made a few changes, including adding a new checkbox to allow verbose time units (12 hours, 34 minutes, 56 seconds instead of 12:34:56) as well as a 'Format' field that lets you specify the time format in HH:MM:SS.  You can also use H:M:S which will eliminate leading zeroes for single-digit time.

Also updated the readme, so more information is available there.

It seems to work fine, but before I drop a new release, I'd appreciate a beta-test. :)

**Comment by MarioMey** [comment]
Wow! Pulling it right now!

**Comment by MarioMey** [comment]
It's great what you modified. But... I would like to use some other format. First at all, I speak spanish, so, I would want to use "minutos" and "segundos". That is not possible, unless I change the code (I can, but maybe some other one can't). It would be nice to have a more flexible format like: "%H:%M:%s" or "%m minutos\n%m segundos...". Something similar to strftime() format. But, if this uses so much time to you, there is no problem. I could make a workaround (I found "_time" and I can make the "if" sentences by myself).

And there is the...

### "Show units" bug:

Look at this:
![imagen](https://user-images.githubusercontent.com/4954109/82504908-e7bdb280-9ad2-11ea-82cf-ada5c4685d78.png)
And this:
![imagen](https://user-images.githubusercontent.com/4954109/82504959-ff953680-9ad2-11ea-88e9-91c7f7bc1cec.png)
Look at the last image, the format: "MM:SS" and look at what's printing: "hours" where should be "minutes" and "minutes" where should be "seconds".

**Comment by MarioMey** [comment]
### "Text Source" bug:
![imagen](https://user-images.githubusercontent.com/4954109/82505881-bf36b800-9ad4-11ea-9ff4-7fd7b27ba71f.png)
Text Source menu is empty and it doesn't work. You click and nothing happens. Now, it is working with my text, I think it's because it was saved in a moment as a setting in the previous version. [EDIT]: in next comment, I say that this is a strange bug. Sometimes it works, sometimes it doesn't.

**Comment by MarioMey** [comment]
I don't really understand last "Text Source" bug... sometimes it works, sometimes it doesn't.

But I found 2 bugs:
-  Button "Reset" doesn't work with "Date/Time". I have to refresh scripts with Refresh OBS button.
- With "Date/Time" and "MM:SS" format, End Text isn't shown. It is with the default format "HH:MM:SS".

Anyway, I set "MM:SS" format and added this text to get what I want:

    # Line 380
	if _time.startswith('00:0'):
		new_time = _time.split(':')[1][1:] + ' segundos'
	elif _time.startswith('00:'):
		new_time = _time.split(':')[1] + ' segundos'
		
	elif _time.startswith('0'):
		new_time = _time.split(':')[0][1:] + ' minutos\n'
		if _time.split(':')[1].startswith('0'):
			new_time = new_time + _time.split(':')[1][1:] + ' segundos'
		else:
			new_time = new_time + _time.split(':')[1] + ' segundos'
	_time = new_time

I've got:
![imagen](https://user-images.githubusercontent.com/4954109/82512435-84d61680-9ae6-11ea-89be-6db0ee1f22b3.png)

... and:
![imagen](https://user-images.githubusercontent.com/4954109/82512451-8ef81500-9ae6-11ea-8d29-fb98c73473c2.png)

But, as I said above, "End Text" still doesn't work.

**Comment by joelgraff** [comment]
The text source bug confuses me, too.  I think if you reload the script or something, it should work.  I'll see if I can come up with something to support other languages.

Some of those other bugs are odd - I didn't see them when I was testing.  I'll take a look at that, too.

**Comment by joelgraff** [comment]
Ok, so I just managed to get a little of this working better.

Changes:

The format field allows strftime formatting.  Note the '%D' allows for days to be displayed in the countdown.  It's not supported by strftime, so I handle that with custom code.  Otherwise, it should behave as you expect.

Also, the checkbox ('show units') has been changed to 'Hide Zero Units'.  This will hide any time units that are zero *unless* they are the last unit in the line, or the previous unit is still non-zero.

Thus, 3 hours, 0 minutes, 10 seconds will remain unchanged, but 0 hours, 0 minutes and 10 seconds will render as '10 seconds'.  It also means that if the format is %H.%M, '00 minutes'  will remain on screen until the 10 seconds finishes counting down.

Finally, fixed the date/time clock so it switches to the end text when done.

Pull it and give it a try.  I have yet to address the other issues you've pointed out.

**Comment by MarioMey** [comment]
Pulling it!

### Bug?
When it reach 0, it shows "0 seconds". But, in that moment, end text should appear. If not, there is one extra second, isn't it?

#### Another thing
This is about a decision design: what do you prefer?
`10 minutes, 0 seconds`
`9 minutes, 60 seconds`

I prefer the second one.

**Comment by MarioMey** [comment]
> The format field allows strftime formatting. Note the '%D' allows for days to be displayed in the countdown. It's not supported by strftime, so I handle that with custom code. Otherwise, it should behave as you expect.

What about %d? I look at [Python datetime docs](https://docs.python.org/3/library/datetime.html#datetime.timedelta) and there it is.

> Also, the checkbox ('show units') has been changed to 'Hide Zero Units'. This will hide any time units that are zero unless they are the last unit in the line, or the previous unit is still non-zero.

Also this?
![imagen](https://user-images.githubusercontent.com/4954109/82613573-fde37580-9b9b-11ea-9d0f-e8997ba1c2ce.png)
Doesn't "02:09" should be "2:09?

> Finally, fixed the date/time clock so it switches to the end text when done.

Excelent.

**Comment by joelgraff** [comment]
I'll take a look at your other issues this week.

Regarding 02:09 vs 2:09, it looks like I missed an edge case.

On the 10 mins 0 sec vs 9 min 60 sec, I think that's a convention that varies by locale, or maybe just personal preference?  I've never seen 10 minutes expressed as 9 minutes, 60 seconds...  However, I can add an option to allow that as well.

Does the end text show properly now?

**Comment by MarioMey** [comment]
Yes, you are right. My phone countdown shows "1:00", then "0:59". But, as I told you, when it goes to "0:00", it should show the end text directly.

> Does the end text show properly now?

Yes!

**Comment by joelgraff** [comment]
> Yes, you are right. My phone countdown shows "1:00", then "0:59". But, as I told you, when it goes to "0:00", it should show the end text directly.
> 
> > Does the end text show properly now?
> 
> Yes!
The end text does show correctly... so I presume you are talking about how it shows "0 seconds" for the last second.

What's happening is the timer is displaying only the integer portion of the second - thus 0.99 seconds would be rendered as "0 seconds".  I think you want to see 0.01 - 0.99 seconds = 1 second, 1.01 - 1.99 seconds = 2 seconds, etc.

Technically, either solution is correct.  The lack of accuracy is due to a lack of unit precision.  I can try to add an option to round up / round down the last time unit, though addressing this completely gets a bit complicated.

**Comment by joelgraff** [comment]
> Doesn't "02:09" should be "2:09?

I took a closer look.  If you want to omit leading zeroes, you can specify a minus sign in the format code.  For example, %-m:%s will give you what you want.

**Comment by joelgraff** [comment]
Pushed changes to fix some of these issues.  Take a look when you get a chance.  I appreciate it!

**Comment by joelgraff** [comment]
At this point, I see no further issues, apart from the end text dropdown not seeing the sources.  I'm going to close this issue for the time being.

**Comment by MarioMey** [comment]
> What's happening is the timer is displaying only the integer portion of the second - thus 0.99 seconds would be rendered as "0 seconds". I think you want to see 0.01 - 0.99 seconds = 1 second, 1.01 - 1.99 seconds = 2 seconds, etc.

When you countdown from "3" to "fire!" with your voice, what do you say? Please, close your eyes and make the countdown talking loud 😂.

 |
 |
 |
V

Select what you did say:
- "3, 2, 1, fire!" or...
- "3, 2, 1, 0, fire!"

Just that. Nothing to add, your honor.

**Comment by MarioMey** [comment]
Thanks for the updates and fixes! ♥

**Comment by joelgraff** [comment]
> > What's happening is the timer is displaying only the integer portion of the second - thus 0.99 seconds would be rendered as "0 seconds". I think you want to see 0.01 - 0.99 seconds = 1 second, 1.01 - 1.99 seconds = 2 seconds, etc.
> 
> When you countdown from "3" to "fire!" with your voice, what do you say? Please, close your eyes and make the countdown talking loud joy.
> 
> |
> |
> |
> V
> 
> Select what you did say:
> 
>     * "3, 2, 1, fire!" or...
> 
>     * "3, 2, 1, 0, fire!"
> 
> 
> Just that. Nothing to add, your honor.

Ummm.. I don't do that. :)  Maybe watch a few youtube livestreams to see what they do!
